# Generated by Django 4.2.4 on 2023-10-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='dscription',
            new_name='desc',
        ),
    ]
