# Generated by Django 4.2.4 on 2023-10-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='blog',
            new_name='comment',
        ),
    ]
